#+LATEX_HEADER: \usepackage{placeins}
#+TITLE: Assignment 3
#+SUBTITLE: CSC 520 Spring 2022 001
#+AUTHOR: Nathan Vercaemert
#+DATE: 2022-04-05
* Question 1
** a.
1. \(tea(BlackTea) \land (\forall x \:cheese(x) \Rightarrow \lnot tea(x))\)
2. \(blend(BlackTea, GreenTea)\)
3. \(\forall x,y \: (\lnot tea(x) \land tea(y)) \Rightarrow \lnot blend(y,x)\)
4. \(\exists x \: tea(x) \land unoxidize(x) \land \lnot wilted(x)\)
5. \(\exists x \forall y \: tea(x) \land ((tea(y) \land \lnot unoxidize(y)) \Rightarrow blend(x,y))\)
** b.
*** 1.
- \(tea(BlackTea) \land (cheese(x) \Rightarrow \lnot tea(x))\)
- \(tea(BlackTea) \land (\lnot cheese(x) \lor \lnot tea(x))\)
*** 2.
- \(blend(BlackTea, GreenTea)\)
*** 3.
- \((\lnot tea(x) \land tea(y)) \Rightarrow \lnot blend(y,x)\)
- \(\lnot(\lnot tea(x) \land tea(y)) \lor \lnot blend(y,x)\)
- \((tea(x) \lor \lnot tea(y)) \lor \lnot blend(y,x)\)
- \(tea(x) \lor \lnot tea(y) \lor \lnot blend(y,x)\)
*** 4.
- \(tea(T1) \land unoxidize(T1) \land \lnot wilted(T1)\)
*** 5.
- \(tea(T2) \land ((tea(y) \land \lnot unoxidize(y)) \Rightarrow blend(T2,y))\)
- \(tea(T2) \land (\lnot(tea(y) \land \lnot unoxidize(y)) \lor blend(T2,y))\)
- \(tea(T2) \land ((\lnot tea(y) \lor unoxidize(y)) \lor blend(T2,y))\)
- \(tea(T2) \land (\lnot tea(y) \lor unoxidize(y) \lor blend(T2,y))\)
** c.
In order to prove by resolution, we introduce the following to our KB:
1. \(blend(BlackTea,cheese(x))\)
note that there is implied universal quantification
*** Also in our knowledge base
- 2. \(tea(BlackTea)\)
- 3. \(\lnot tea(cheese(x))\)
*** Standardized for resolution
- 4. \(tea(z) \lor \lnot tea(y) \lor \lnot blend(y,z)\)
*** Resolution
- 3. \(tea(z) \lor \lnot tea(y) \lor \lnot blend(y,z)\) resolves with 2. \(tea(BlackTea)\)
- this leaves 4. \(tea(z) \lor \lnot blend(BlackTea,z)\) after the substitution \({y/BlackTea}\)
- 4. \(tea(z) \lor \lnot blend(BlackTea,z)\) resolves with 3. \(\lnot tea(cheese(x))\)
- this leaves 5. \(\lnot blend(BlackTea,cheese(x))\) after the substitution \({z/cheese(x)}\)
- 5. \(\lnot blend(BlackTea,cheese(x))\) resolves with 1. \(blend(BlackTea,cheese(x))\)
- this leaves the empty set
- this proves that cheese does not blend with BlackTea.
**** Note
\(cheese(x)\) is being used in place of any instatiation of x that would be true in our world. It is implied that we have at least one object \(C\) that maps to a cheese, so where I use \(cheese(x), cheese(C)\) could be substituted. This could equivalently simply be \(C\) as the problem's use of "cheese" could simply be a constant. The problem's use of "cheese" is not clear in this respect. The resolution works conceptually either way. Similarly a Skolem function could be used, cheese(C(x)). If it is required that I pick one, simply "C" is the most clear because Sentence 1 in the question refers to cheese as a constant like BlackTea.
* Question 2
- Note that I use PL-FOL to refer to propositionalization.
- Note that "mp" stands for Modus Ponens.
** a.
*** Provided Sentences in FOL
- Sentence 1: \(\forall x \: o(x) \Rightarrow l(x)\)
- Sentence 2: \(\forall x \: o(x) \Rightarrow d(x)\)
- Sentence 3: \(\forall x \: (o(x) \land i(x)) \Rightarrow s(x)\)
- Sentence 3 simplified: \(\forall x \: i(x) \Rightarrow s(x)\)
- The remaining sentences will take this simplified approach. It is a safe assumption that our model does not have any assignments that would complicate these simplifications.
- From Sentence 5: \(\forall x \: o(x) \Rightarrow (g(x) \lor si(x))\)  
- From Sentence 8: \(\forall x \: (g(x) \land i(x)) \Rightarrow pre(x)\)
- From Sentence 8: \(\forall x \: si(x) \Rightarrow \lnot pre(x)\)
*** Provided sentences that can be interpreted in terms of PL-FOL
- Sentence 4: \(\lnot s(C)\)
- Sentence 6: \(o(C)\)
- Sentence 7: \(g(C) \land \lnot i(C) \land \lnot s(C) \land \lnot pre(C)\)
*** FOL Sentences instantiated into PL (Carol is the only customer, so she is the only instatiation that matters)
- Sentence 1 PL-FOL: \(o(C) \Rightarrow l(C)\)
- Sentence 2 PL-FOL: \(o(C) \Rightarrow d(C)\)
- Sentence 3 PL-FOL: \(i(C) \Rightarrow s(C)\)
- Sentence 5 PL-FOL: \(o(C) \Rightarrow (g(C) \lor si(C))\)
- From Sentence 8 PL-FOL: \((g(C) \land i(C)) \Rightarrow pre(C)\)
- From Sentence 8 PL-FOL: \(si(C) \Rightarrow \lnot pre(C)\)
*** Example: Carol can collect loyalty points (Sentence 1. combined with Sentence 6.)
- Sentence 1. is a FOL statement: \(\forall x \: o(x) \Rightarrow l(x)\)
- Sentence 6. can be interpreted as  a PL statement: \(o(C)\) (This is true in our truth table for the consistent model.)
- Since Carol is the only object that's a customer in our model, the only instantiation of Sentence 1. that adds value is the following: \(o(C) \Rightarrow l(C)\)
- Thus, in our model's truth table, \(l(C)\) is true.
- This is an example of how we will use the provided sentences to prove that a our model is consistent.
- Note that this example is not critical because there are no other statements that involve \(l(C)\) in PL-FOL
*** Truth table to show a consistent model.
- No statement contradicts another statement.
- S0 referes to "Statement 0" not "Sentence 0"
- (S2) refers to the combination of decomposition of S2 and the definition of implication to the current statement.
- Further explanation to why S5-8 are T was deemed unnecessary as it follows from basic PL.
\FloatBarrier
| Ref      | PL-FOL                                                        | T/F    |
|----------+---------------------------------------------------------------+--------|
| S0       | \(\lnot s(C)\)                                                | T      |
| S1       | \(o(C)\)                                                      | T      |
| S2       | \(g(C) \land \lnot i(C) \land \lnot s(C) \land \lnot pre(C)\) | T      |
| S3       | \(o(C) \Rightarrow l(C)\)                                     | T      |
| S1 mp S3 | \(l(C)\)                                                      | T      |
| S4       | \(o(C) \Rightarrow d(C)\)                                     | T      |
| S1 mp S4 | \(d(C)\)                                                      | T      |
| S5       | \(i(C) \Rightarrow s(C)\)                                     | T (S2) |
| S6       | \(o(C) \Rightarrow (g(C) \lor si(C))\)                        | T (S2) |
| S7       | \((g(C) \land i(C)) \Rightarrow pre(C)\)                      | T (S2)  |
| S8       | \(si(C) \Rightarrow \lnot pre(C)\)                            | T (S2) |
\FloatBarriers
**** Note
As FOL statements have either true/false values, they could have been used in place of their propositionalized counterparts. I have universally instantiated with C because the language makes more sense and it doesn't change the values for their corresponding T/F.
** b.
Assuming SO has been replaced with \(s(C)\), we can prove that there is a contradiction with the following resolution:
Consider S0* to be \(s(C)\)
*** Resolution
- With decomposition we can move from S2 to \(\lnot s(C)\)
- Consider S2* to be \(\lnot s(C)\)
- S2* resolves with S0* to the empty set, thus we have a contradiction and our model is not consistent
* Question 3
- FOR matches solutions
- MAC incorporates the same tweaks necessary to match FOR solutions but uses slightly different algorithm than TAs.
- Execution instructions and solutions locations explained:
#+BEGIN_SRC shell
  ./README.pdf
#+END_SRC
* VCL
Execution was tested on the Linux Lab machine.
